/**
 * frame功能
 */
export const APP_SIDEMENU_SWITCH = 'APP_SIDEMENU_SWITCH'
export const UPDATE_VISITED_SUBMENU_LIST = 'UPDATE_VISITED_SUBMENU_LIST'
export const DELETE_VISITED_SUBMENU = 'DELETE_VISITED_SUBMENU'
