/**
 * frame功能
 */
export const APP_SIDEMENU_SWITCH = 'APP_SIDEMENU_SWITCH'
// 初始化菜单是否收起
export const INIT_APP_SIDEMENU_SWITCH = 'INIT_APP_SIDEMENU_SWITCH'
// 初始化 访问过的菜单
export const INIT_VISITED_SUBMENU_LIST = 'INIT_VISITED_SUBMENU_LIST'
export const UPDATE_VISITED_SUBMENU_LIST = 'UPDATE_VISITED_SUBMENU_LIST'
export const DELETE_VISITED_SUBMENU = 'DELETE_VISITED_SUBMENU'
